# Generated by Django 3.1.7 on 2021-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=120, unique=True)),
                ('password', models.TextField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
